spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      idle-timeout: 20
      maximum-pool-size: 100
      minimum-idle: 10
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
